version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/casc.yaml:/var/jenkins_conf/casc.yaml
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dcloud.config.dir=/var/jenkins_conf
      - CASC_JENKINS_CONFIG=/var/jenkins_conf/casc.yaml
    networks:
      - test-network

  selenium-hub:
    image: selenium/hub:4.15
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - test-network
    environment:
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300

  chrome:
    image: selenium/node-chrome:4.15
    shm_size: '2gb'
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - START_XVFB=false
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - test-network

  appium:
    image: appium/appium:latest
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
    ports:
      - "4723:4723"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  jenkins_home: