pipeline {
    agent any

    parameters {
        booleanParam(name: 'RUN_API_TESTS', defaultValue: true, description: 'Run API Tests')
        booleanParam(name: 'RUN_WEB_TESTS', defaultValue: true, description: 'Run Web Tests')
        booleanParam(name: 'RUN_MOBILE_TESTS', defaultValue: false, description: 'Run Mobile Tests')
        choice(name: 'TEST_ENV', choices: ['qa', 'staging', 'prod'], description: 'Test Environment')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('API Tests') {
            when { expression { params.RUN_API_TESTS } }
            steps {
                script {
                    sh """
                        cd api-tests
                        mvn clean test -Denv=${params.TEST_ENV}
                    """
                }
            }
            post {
                always {
                    junit 'api-tests/target/surefire-reports/*.xml'
                    cucumber 'api-tests/target/cucumber-reports/CucumberTestReport.json'
                }
            }
        }

        stage('Web Tests') {
            when { expression { params.RUN_WEB_TESTS } }
            steps {
                script {
                    sh """
                        cd web-tests
                        mvn clean test -Denv=${params.TEST_ENV}
                    """
                }
            }
            post {
                always {
                    junit 'web-tests/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Mobile Tests') {
            when { expression { params.RUN_MOBILE_TESTS } }
            steps {
                script {
                    sh """
                        cd mobile-tests
                        mvn clean test -Denv=${params.TEST_ENV}
                    """
                }
            }
            post {
                always {
                    junit 'mobile-tests/target/surefire-reports/*.xml'
                    cucumber 'mobile-tests/target/cucumber-reports/mobile/cucumber.json'
                }
            }
        }
    }

    post {
        always {
            // Archive test results
            archiveArtifacts artifacts: '**/target/cucumber-reports/**/*', allowEmptyArchive: true
        }
    }
}